-- Insertion of the data in the table Cocktail
INSERT INTO Cocktail (Name_Cocktail, Origin_Cocktail, Difficulty_Cocktail, Price_Cocktail) VALUES
('Piña Colada','Kingdom of Mulgi', 5,345 ),
('Moscow Mule','Principalty of Tanlakkia' ,6, 576),
('Cosmopolitan','Grand Duchy of Yenhingia' ,7, 814),
('Bloody Mary','Heptarchy of Nurupia', 8, 546),
('Tequila Sunrise','Kingdom of Mulgi', 4, 265),
('Mojito','Kingdom of Wehia',  4, 342),
('Margarita','Republic of Anovaleli',  6,  437),
('Blue lagoon','Kingdom of Mulgi', 3, 661),
('Gin Fizz','Republic of Anovaleli', 2,276),
('Planter Punch','Bozbeyurt Horde', 5, 341),
('Gin Tonic','Republic of Anovaleli', 1, 270),
('Americano','Principalty of Tanlakkia', 4,  335),
('Mai-Tai','Yiunyian Theocracy', 3,  486),
('Sex on the Beach','Heptarchy of Nurupia', 4,  733),
('Espresso Martini','Principalty of Tanlakkia',  6,  600),
('Spritz','Federation of Raf', 5,  280),
('Sangria','Federation of Raf', 4,  488),
('Rusty Nail','Republic of Kuridia',8, 470),
('Irish Coffee','Heptarchy of Nurupia', 4, 600),
('White Lady','Jaheds', 7,  461);

-- Delete from Dose where ID_Dose >= 1;

-- Insertion of the data in the table Ingredient
INSERT INTO Ingredient (Name_Ingredient, Origin_Ingredient, Rank_Ingredient, Type_Ingredient, Degre_Ingredient, Quest_Ingredient, Price_Ingredient) VALUES
('Tequila','Bozbeyurt Horde', 5, 'Alcohol', 45, 19, 200),
('Orange Juice','Kingdom of Wehia', 2, 'Juice', 0, 7, 30),
('Grenadine Syrup','Jaheds', 4, 'Syrup', 0, 15, 35),
('Rhum','Kingdom of Mulgi', 7, 'Alcohol', 40, 6, 250),
('Lemon','Kingdom of Wehia', 2, 'Fruit', 0, 4, 10 ),
('Mint','Principality of Tanlakkia', 1, 'Aromate', 0, 5, 15),
('Sparkling Water','Federation of Raf', 5, 'Water', 0, 17, 40),
('Cointreau','Grand Duchy of Yenhingia', 6, 'Alcohol', 40, 20, 225),
('Lime Juice','Kingdom of Wehia', 2, 'Juice', 0, 8, 11),
('Vodka','Imamah of Bay', 8, 'Alcohol', 40, 39, 500),
('Whisky','Imamah of Bay', 8, 'Alcohol', 40, 38, 450),
('Blue Curacao','Kingdom of Mulgi', 5, 'Alcohol', 35, 37, 150),
('Lemon Juice','Kingdom of Wehia', 2, 'Juice', 0, 9, 11),
('Coconut Cream','Heptarchy of Nurupia ', 3, 'Special', 0, 36, 50),
('Pineapple Juice','Grand Duchy of Yenhingia', 4, 'Juice', 0, 10, 45),
('Gin','Republic of Anovaleli', 7, 'Alcohol', 40, 35, 225),
('Tonic','Hamyueolguk Theocracy', 5, 'Alcohol', 0, 34, 45),
('Tomato Juice','Federation of Raf', 3, 'Juice', 0, 11, 35),
('Campari','Republic of Anovaleli', 5, 'Alcohol', 28.5, 33, 120),
('Red Vermouth','Republic of Kuridia', 5, 'Alcohol', 16, 32, 175),
('White Curacao','Kingdom of Mulgi',5, 'Alcohol', 40, 31, 150),
('Orgeat Syrup','Federation of Raf', 6, 'Syrup', 0, 13, 75),
('Ginger Beer','Principalty of Tanlakkia', 5, 'Soda', 0, 30, 65),
('Peach Liquor','Yiunyian Theocracy', 4, 'Alcohol', 18, 21,125),
('Cranberry Juice','Republic of Anovaleli', 3, 'Juice', 0, 12, 78),
('Kahlua','Kingdom of Wehia', 5, 'Alcohol', 30, 29, 120),
('Coffee','Heptarchy of Nurupia', 4, 'Nut', 0, 14, 25),
('Sugar Syrup','Republic of Kuridia', 2, 'Syrup', 0, 16, 30),
('Aperol','Jaheds', 6, 'Alcohol', 11, 28, 80),
('Prosecco','Republic of Anovaleli', 7, 'Alcohol', 10, 27, 160),
('Red Wine','Jaheds', 8, 'Alcohol', 13, 22, 180),
('Cognac','Jaheds', 8, 'Alcohol',45, 23, 250),
('Lemonade','Kingdom of Mulgi', 5, 'Soda', 0, 18, 35),
('Fresh Fruits','Kingdom of Wehia', 1, 'Fruit', 0, 3, 23),
('Scotch','Bozbeyurt Horde', 6, 'Alcohol', 40, 24, 300),
('Drambuie','Republic of Kuridia', 5, 'Alcohol', 40, 25, 170),
('Sour Cream','Jaheds', 5, 'Special', 0,26, 100),
('Ice Crush','Imamah of Bay', 1, 'Water', 0, 1, 10),
('Sugar','Republic of Kuridia', 2, 'Syrup', 0, 2, 15);

-- Insertion of the data in the table Dose
INSERT INTO Dose (ID_Dose, Quantity_Dose, Unit_Dose, Name_Cocktail, Name_Ingredient) VALUES
(1,4,'cl','Piña Colada','Rhum'),
(2,4,'cl','Piña Colada','Coconut Cream'),
(3,7,'cl','Piña Colada','Pineapple Juice'),
(4,5,'cl','Moscow Mule','Vodka'),
(5,2,'cl','Moscow Mule','Lemon Juice'),
(6,8,'cl','Moscow Mule','Ginger Beer'),
(7,2,'cl','Cosmopolitan','Vodka'),
(8,2,'cl','Cosmopolitan','Cointreau'),
(9,2,'cl','Cosmopolitan','Cranberry Juice'),
(10,1,'cl','Cosmopolitan','Lime Juice'),
(11,5,'cl','Bloody Mary','Vodka'),
(12,2,'cl','Bloody Mary','Lemon Juice'),
(13,8,'cl','Bloody Mary','Tomato Juice'),
(14,5,'cl','Tequila Sunrise','Tequila'),
(15,9,'cl','Tequila Sunrise','Orange Juice'),
(16,1,'cl','Tequila Sunrise','Grenadine Syrup'),
(17,5,'cl','Mojito','Rhum'),
(18,3,'cl','Mojito','Lime Juice'),
(19,8,'wedge','Mojito','Mint'),
(20,3,'wedge','Mojito','Lemon'),
(21,2,'spoon','Mojito','Sugar'),
(22,5,'cl','Mojito','Sparkling Water'),
(23,4,'cl','Margarita','Tequila'),
(24,2,'cl','Margarita','Cointreau'),
(25,2,'cl','Margarita','Lime Juice'),
(26,4,'cl','BLue Lagoon','Vodka'),
(27,2,'cl','BLue Lagoon','Blue Curacao'),
(28,1,'cl','BLue Lagoon','Lemon Juice'),
(29,6,'cl','Gin Fizz','Gin'),
(30,2,'cl','Gin Fizz','Lemon Juice'),
(31,2,'cl','Gin Fizz','Sugar Syrup'),
(32,5,'cl','Gin Fizz','Sparkling Water'),
(33,5,'cl','Gin Tonic','Gin'),
(34,10,'cl','Gin Tonic','Tonic'),
(35,4,'cl','Planter Punch','Rhum'),
(36,4,'cl','Planter Punch','Orange Juice'),
(37,4,'cl','Planter Punch','Pineapple Juice'),
(38,2,'cl','Planter Punch','Lemon Juice'),
(39,1,'cl','Planter Punch','Grenadine Syrup'),
(40,4,'cl','Americano','Campari'),
(41,4,'cl','Americano','Red Vermouth'),
(42,6,'cl','Americano','Sparkling Water'),
(43,6,'cl','Mai-Tai','Rhum'),
(44,2,'cl','Mai-Tai','White Curacao'),
(45,2,'cl','Mai-Tai','Orgeat Syrup'),
(46,2,'cl','Mai-Tai','Lime Juice'),
(47,4,'cl','Sex on the Beach','Vodka'),
(48,2,'cl','Sex on the Beach','Peach Liquor'),
(49,5,'cl','Sex on the Beach','Cranberry Juice'),
(50,5,'cl','Sex on the Beach','Orange Juice'),
(51,3,'cl','Espresso Martini','Vodka'),
(52,2,'cl','Espresso Martini','Kahlua'),
(53,6,'cl','Espresso Martini','Coffee'),
(54,1,'cl','Espresso Martini','Sugar Syrup'),
(55,6,'cl','Spritz','Prosecco'),
(56,4,'cl','Spritz','Aperol'),
(57,2,'cl','Spritz','Sparkling Water'),
(58,75,'cl','Sangria','Red Wine'),
(59,8,'cl','Sangria','Cognac'),
(60,4,'wedge','Sangria','Lemon'),
(61,10,'wedge','Sangria','Fresh Fruits'),
(62,20,'cl','Sangria','Lemonade'),
(63,4.5,'cl','Rusty Nail','Scotch'),
(64,2.5,'cl','Rusty Nail','Drambuie'),
(65,3,'cl','Irish Coffee','Whisky'),
(66,11,'cl','Irish Coffee','Coffee'),
(67,1,'cl','Irish Coffee','Sugar Syrup'),
(68, 5, 'cl', 'Irish Coffee', 'Sour Cream'),
(69,4, 'cl', 'White Lady', 'Gin'),
(70,2, 'cl', 'White Lady', 'Cointreau'),
(71,1, 'cl', 'White Lady', 'Lemon Juice');
